name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Check if version exists
        run: |
          VERSION=$(python setup.py --version)
          if pip index versions chatgpt-md-converter 2>/dev/null | grep -q "^chatgpt-md-converter ($VERSION)$"; then
            echo "Version $VERSION already exists on PyPI"
            exit 1
          fi

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
