name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1